### PR TITLE
go-github v39

### LINKED ISSUE #2: required_conversation_resolution is ignored
If I set `required_conversation_resolution: true` the setting does not change. Possibly fixed in a newer version of go-github, but I'm not super familiar with go. https://github.com/google/go-github/releases/tag/v38.0.0

### PR DESCRIPTION
**Pull request by tobyw4n**
Updated go-github references to v39. Ran `go get` and `go mod tidy`. 

Closes #2

### CODE REVIEW

**Comment by Hatzelencio** [comment]
Hi @tobyw4n LGTM. 

There is only one thing left to do. You will need to update the `README.md` file at versions coincidences with `v0.0.0`. I suggest updating up to `v1.0.0` version at lines: 3, 58, 74, 90, 104.

**Comment by tobyw4n** [comment]
@Hatzelencio thanks for the quick review. I have updated the README

**Review by Hatzelencio — APPROVED** [review]

**Comment by Hatzelencio** [comment]
Hi, @tobyw4n I approved and ran your PR but in the Continuous Integration step it failed, but the other steps ran successfully. If you want, I can accept your PR with a failing lint step, or if you prefer you could repair the linting step. As you wish 😄

**Comment by tobyw4n** [comment]
It looks like that action's repo disappeared. I'm not sure of a suitable replacement.

**Pull request merged**
